golang-kata:
  image: golang:1.10
  stage: test
  before_script:
    - cp -a /builds/liuwill/* /go/src/
    - cd /go/src/go-kata-practice
    - go get -t -v ./...
  script:
    - make coverhtml
  artifacts:
    paths:
      - dist/

# lint_code:
#   stage: test
#   script:
#     - make lint

pages:
  stage: deploy
  dependencies:
    - golang-kata
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
