variables:
  REPO_NAME: go-kata-practice

golang-kata:
  image: golang:1.10
  stage: test
  before_script:
    - mkdir /go/src/${REPO_NAME}
    - cp -a ${CI_PROJECT_DIR}/* /go/src/${REPO_NAME}/
    - cd /go/src/${REPO_NAME}/
    - go get -t -v ./...
  script:
    - make coverhtml
    - mkdir ${CI_PROJECT_DIR}/dist
    - cp -a /go/src/${REPO_NAME}/dist/* ${CI_PROJECT_DIR}/dist/
  artifacts:
    paths:
      - dist/

# lint_code:
#   stage: test
#   script:
#     - make lint

pages:
  stage: deploy
  dependencies:
    - golang-kata
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
